global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Wpf.ViewModels;
global using Wpf.Services;
global using Wpf.Commands;
global using Wpf.Configs;