name: Publish NuGet Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Update package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
      
    - name: Build
      run: |
        dotnet build Kanadeiar.Core  -c Release
        dotnet build Tests/Kanadeiar.Core.Tests -c Release
      
    - name: Test
      run: dotnet test Tests/Kanadeiar.Core.Tests --no-build -c Release -v normal
      
    - name: Pack
      run: dotnet pack Kanadeiar.Core -c Release --no-build -v normal
      
    - name: Publish
      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetApiKey }} -n --skip-duplicate -s https://api.nuget.org/v3/index.json
